module.exports = {
  extends: [
    'tslint:recommended',
    'tslint-eslint-rules',
    'tslint-react',
    'tslint-consistent-codestyle'
  ],
  rulesDirectory: [
    'node_modules/tslint-microsoft-contrib'
  ],
  rules: {
    'quotemark': [true, 'single', 'avoid-escape', 'jsx-single'],
    'ordered-imports': false,
    'object-literal-sort-keys': false,
    'no-unused-variable': true,
    'trailing-comma': [true, {
      'multiline': 'never',
      'singleline': 'never'
    }],
    'indent': [true, 'spaces', 2],
    'no-empty-interface': false,
    'jsx-alignment': false,
    'jsx-curly-spacing': [true, 'never'],
    'jsx-no-multiline-js': false,
    'jsx-no-lambda': true,
    'jsx-no-string-ref': true,
    'jsx-no-bind': true,
    'jsx-self-close': true,
    'jsx-wrap-multiline': true,
    'no-unnecessary-else': true,
    'no-return-undefined': true,
    'no-static-this': true,
    'prefer-const-enum': true,
    'insecure-random': true,
    'no-constant-condition': true,
    'no-control-regex': true,
    'no-cookies': true,
    'no-delete-expression': true,
    'no-disable-auto-sanitization': true,
    'no-document-domain': true,
    'no-document-write': true,
    'no-duplicate-case': true,
    'no-empty-line-after-opening-brace': true,
    'no-exec-script': true,
    'no-for-in': true,
    'no-function-constructor-with-string-args': true,
    'no-increment-decrement': true,
    'no-inner-html': true,
    'no-invalid-regexp': true,
    'no-regex-spaces': true,
    'no-reserved-keywords': true,
    'no-stateless-class': true,
    'no-string-based-set-immediate': true,
    'no-string-based-set-interval': true,
    'no-string-based-set-timeout': true,
    'no-unnecessary-bind': true,
    'no-unnecessary-field-initialization': true,
    'no-unnecessary-local-variable': true,
    'no-unnecessary-override': true,
    'no-useless-files': true,
    'no-with-statement': true,
    'non-literal-require': true,
    'possible-timing-attack': true,
    'prefer-array-literal': true,
    'promise-must-complete': true,
    'react-a11y-anchors': true,
    'react-a11y-aria-unsupported-elements': true,
    'react-a11y-event-has-role': true,
    'react-a11y-image-button-has-alt': true,
    'react-a11y-img-has-alt': true,
    'react-a11y-lang': true,
    'react-a11y-meta': true,
    'react-a11y-props': true,
    'react-a11y-proptypes': true,
    'react-a11y-role-has-required-aria-props': true,
    'react-a11y-role-supports-aria-props': true,
    'react-a11y-role': true,
    'react-a11y-tabindex-no-positive': true,
    'react-a11y-titles': true,
    'react-anchor-blank-noopener': true,
    'react-iframe-missing-sandbox': true,
    'react-no-dangerous-html': true,
    'react-this-binding-issue': true,
    'react-unused-props-and-state': true,
    'underscore-consistent-invocation': true,
    'use-named-parameter': true,
    'valid-typeof': true,
    'no-bitwise': false,
    'no-shadowed-variable': false
  }
};
